// packages/vue-app/src/components/CheckoutForm.vue
<script setup lang="ts">
import { useForm, useField } from 'vee-validate';
import { toTypedSchema } from '@vee-validate/zod';
import * as z from 'zod';
import { useI18n } from 'vue-i18n';
import { useAuthStore } from '@/stores/auth';
import { useConfiguratorStore } from '@/stores/configurator';

const { t } = useI18n();
const authStore = useAuthStore();
const configStore = useConfiguratorStore();

const validationSchema = toTypedSchema(
  z.object({
    name: z.string().min(1, t('checkout.errors.required')),
    email: z.string().min(1, t('checkout.errors.required')).email(t('checkout.errors.email')),
    company: z.string().optional(),
    terms: z.boolean().refine(val => val === true, {
      message: t('checkout.errors.terms')
    })
  })
);

const { handleSubmit, isSubmitting } = useForm({
  validationSchema,
  initialValues: {
    name: authStore.user?.name || '',
    email: authStore.user?.email || '',
    company: '',
    terms: false
  }
});

const { value: name, errorMessage: nameError } = useField<string>('name');
const { value: email, errorMessage: emailError } = useField<string>('email');
const { value: company } = useField<string>('company');
const { value: terms, errorMessage: termsError } = useField<boolean>('terms');

const onSubmit = handleSubmit(values => {
  const payload = {
    customer: values,
    order: {
      tariff: configStore.selectedTariff,
      addons: configStore.selectedModules,
      totalPrice: configStore.totalPrice
    }
  };

  console.log('🚀 API sent:', JSON.stringify(payload, null, 2));
  alert(t('checkout.success'));
});
</script>

<template>
  <form
    @submit="onSubmit"
    class="space-y-5 bg-white p-6 rounded-xl border border-slate-200 shadow-sm"
  >
    <h2 class="text-lg font-semibold text-slate-800 border-b border-slate-100 pb-3">
      {{ $t('checkout.title') }}
    </h2>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
      <div>
        <label for="name" class="form-label">{{ $t('checkout.name') }}</label>
        <input
          v-model="name"
          type="text"
          id="name"
          :class="['input-default', nameError ? 'input-border-error' : 'input-border']"
        />
        <p v-if="nameError" class="error-message">{{ nameError }}</p>
      </div>

      <div>
        <label for="email" class="form-label">{{ $t('checkout.email') }}</label>
        <input
          v-model="email"
          type="email"
          id="email"
          :class="['input-default', emailError ? 'input-border-error' : 'input-border']"
        />
        <p v-if="emailError" class="error-message">{{ emailError }}</p>
      </div>
    </div>

    <div>
      <label for="companyName" class="form-label">{{ $t('checkout.company') }}</label>
      <input
        v-model="company"
        type="text"
        id="companyName"
        class="w-full px-3 py-2 rounded-lg border border-slate-300 focus:ring-2 focus:ring-indigo-600 focus:border-transparent outline-none transition-all"
      />
    </div>

    <div>
      <label class="flex items-center gap-2 cursor-pointer">
        <input
          v-model="terms"
          type="checkbox"
          class="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500 border-slate-300"
        />
        <span class="text-sm text-slate-700">{{ $t('checkout.terms') }}</span>
      </label>
      <p v-if="termsError" class="error-message">{{ termsError }}</p>
    </div>

    <div class="pt-4 border-t border-slate-100 flex justify-end">
      <button
        type="submit"
        :disabled="isSubmitting"
        class="px-6 py-2.5 bg-indigo-600 text-white font-semibold rounded-lg hover:bg-indigo-700 transition-colors disabled:opacity-70 cursor-pointer"
      >
        {{ isSubmitting ? '...' : $t('checkout.submit') }}
      </button>
    </div>
  </form>
</template>

<style scoped>
@reference "../style.css";

.input-default {
  @apply w-full px-3 py-2 rounded-lg border outline-none transition-all;
}
.input-border {
  @apply border-slate-300;
  &:focus {
    @apply ring-2 ring-indigo-600;
    border-color: transparent;
  }
}
.input-border-error {
  @apply border-red-500;
  &:focus {
    @apply ring-2 ring-red-200;
  }
}
.error-message {
  @apply text-xs text-red-600 mt-1 font-medium;
}
.form-label {
  @apply block text-sm font-medium text-slate-700 mb-1;
}
</style>

// packages/react-app/src/components/CheckoutForm.tsx
'use client';

import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { useConfiguratorStore } from '@/stores/configurator';

const checkoutSchema = z.object({
  name: z.string().min(1, 'Jméno je povinné'),
  email: z.string().min(1, 'E-mail je povinný').email('Neplatný e-mail'),
  company: z.string().optional(),
  terms: z.literal(true, {
    errorMap: () => ({ message: 'Musíte souhlasit s obchodními podmínkami' })
  })
});

type CheckoutFormValues = z.infer<typeof checkoutSchema>;

export default function CheckoutForm() {
  const selectedTariff = useConfiguratorStore(state => state.selectedTariff);
  const selectedModules = useConfiguratorStore(state => state.selectedModules);

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting }
  } = useForm<CheckoutFormValues>({
    resolver: zodResolver(checkoutSchema),
    defaultValues: {
      name: '', // authStore not used for now
      email: '',
      company: ''
    }
  });

  const onSubmit = (values: CheckoutFormValues) => {
    // Total price calculation
    const base = selectedTariff?.basePrice || 0;
    const addons = selectedModules.reduce((sum, mod) => sum + mod.price, 0);
    const totalPrice = base + addons;

    const payload = {
      customer: values,
      order: {
        tariff: selectedTariff,
        addons: selectedModules,
        totalPrice
      }
    };

    console.log('🚀 API sent:', JSON.stringify(payload, null, 2));
    alert('Objednávka byla úspěšně odeslána!');
  };

  return (
    <form
      onSubmit={handleSubmit(onSubmit)}
      className="space-y-5 bg-white p-6 rounded-xl border border-slate-200 shadow-sm"
    >
      <h2 className="text-lg font-semibold text-slate-800 border-b border-slate-100 pb-3">
        Dokončení objednávky
      </h2>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <div>
          <label htmlFor="name" className="block text-sm font-medium text-slate-700 mb-1">
            Jméno a příjmení
          </label>
          <input
            id="name"
            type="text"
            {...register('name')}
            className={`w-full px-3 py-2 rounded-lg border outline-none transition-all ${
              errors.name
                ? 'border-red-500 ring-2 ring-red-200'
                : 'border-slate-300 focus:ring-2 focus:ring-indigo-600 focus:border-transparent'
            }`}
          />
          {errors.name && (
            <p className="text-xs text-red-600 mt-1 font-medium">{errors.name.message}</p>
          )}
        </div>

        <div>
          <label htmlFor="email" className="block text-sm font-medium text-slate-700 mb-1">
            Pracovní e-mail
          </label>
          <input
            id="email"
            type="email"
            {...register('email')}
            className={`w-full px-3 py-2 rounded-lg border outline-none transition-all ${
              errors.email
                ? 'border-red-500 ring-2 ring-red-200'
                : 'border-slate-300 focus:ring-2 focus:ring-indigo-600 focus:border-transparent'
            }`}
          />
          {errors.email && (
            <p className="text-xs text-red-600 mt-1 font-medium">{errors.email.message}</p>
          )}
        </div>
      </div>

      <div>
        <label htmlFor="companyName" className="block text-sm font-medium text-slate-700 mb-1">
          Název firmy (volitelné)
        </label>
        <input
          id="companyName"
          type="text"
          {...register('company')}
          className="w-full px-3 py-2 rounded-lg border outline-none transition-all"
        />
      </div>

      <div>
        <label htmlFor="terms" className="flex items-center gap-2 cursor-pointer">
          <input
            id="terms"
            type="checkbox"
            {...register('terms')}
            className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500 border-slate-300"
          />
          <span className="text-sm font-medium text-slate-700">
            Souhlasím s obchodními podmínkami
          </span>
        </label>
        {errors.terms && (
          <p className="text-xs text-red-600 mt-1 font-medium">{errors.terms.message}</p>
        )}
      </div>

      <div className="pt-4 border-t border-slate-100 flex justify-end">
        <button
          type="submit"
          disabled={isSubmitting}
          className="px-6 py-2.5 bg-indigo-600 text-white font-semibold rounded-lg
            hover:bg-indigo-700 transition-colors disabled:opacity-70 cursor-pointer"
        >
          {isSubmitting ? '...' : 'Odeslat objednávku'}
        </button>
      </div>
    </form>
  );
}
